#importing libraries.

In [28]:

import pandas as pd
import numpy as np

#reading the file.

In [29]:
df = pd.read_csv("hr_dirty_portfolio.csv")

#checking the file.

In [30]:
display (df)

,employee_id,full_name,department,job_title,hire_date,salary,performance_score,termination_date,unnamed_blank_column_1,sys_audit_dummy_flag,unnamed_blank_column_2
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MISSING_ID,Employee_1107,Human Resources,Recruiter,2021-12-13,-12000.0,Meets,NaN,NaN,NaN,NaN
2,EMP_1739,Employee_1739,Finance,Financial Analyst,2019-04-05,119127.0,Exceeds,NaN,NaN,NaN,NaN
3,EMP_1140,Employee_1140,Finance,Financial Analyst,2022-07-15,114827.0,Needs Improvement,NaN,NaN,NaN,NaN
4,EMP_2018,Employee_2018,Sales,Account Executive,2024-08-31,56382.0,Meets,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1120,EMP_1466,Employee_1466,Marketing,SEO Specialist,2023-01-17,121344.0,Exceeds,NaN,NaN,NaN,NaN
1121,EMP_1121,Employee_1121,Finance,Accountant,2021-01-30,45772.0,Meets,NaN,NaN,NaN,NaN
1122,EMP_2044,Employee_2044,Sales,Sales Manager,Active Employee,136520.0,Needs Improvement,NaN,NaN,NaN,NaN
1123,MISSING_ID,Employee_1352,Engineering,Software Engineer,2021-09-21,-12000.0,Needs Improvement,NaN,NaN,NaN,NaN
1124,EMP_1860,Employee_1860,Human Resources,Recruiter,2026-02-30,149452.0,Meets,NaN,NaN,NaN,NaN

#creating a copy to avoid losing results in the process.

In [31]:
df_original = df.copy()

#getting rid of completely empty rows and columns.

In [32]:
df = df.dropna(how = "all")
df = df.dropna(how = "all", axis =1)

#getting rid of duplicates.

In [34]:
df = df.drop_duplicates()

#replacing empty cells on employee_id column.

In [35]:
df["employee_id"] = df ["employee_id"].replace ("MISSING_ID",pd.NA)
df["employee_id"] = df["employee_id"].fillna (df ["full_name"].str.replace("Employee","EMP", regex = False))

#checking result.

In [52]:
df

,employee_id,full_name,department,job_title,hire_date,salary,performance_score
1,EMP_1107,Employee_1107,Human Resources,Recruiter,2021-12-13,-12000.0,Meets
2,EMP_1739,Employee_1739,Finance,Financial Analyst,2019-04-05,119127.0,Exceeds
3,EMP_1140,Employee_1140,Finance,Financial Analyst,2022-07-15,114827.0,Needs Improvement
4,EMP_2018,Employee_2018,Sales,Account Executive,2024-08-31,56382.0,Meets
5,EMP_1527,Employee_1527,Engineering,Software Engineer,2020-06-29,139659.0,Meets
...,...,...,...,...,...,...,...
1119,EMP_1330,Employee_1330,Sales,Account Executive,2026-02-30,145421.0,Needs Improvement
1120,EMP_1466,Employee_1466,Marketing,SEO Specialist,2023-01-17,121344.0,Exceeds
1121,EMP_1121,Employee_1121,Finance,Accountant,2021-01-30,45772.0,Meets
1122,EMP_2044,Employee_2044,Sales,Sales Manager,Active Employee,136520.0,Needs Improvement
1124,EMP_1860,Employee_1860,Human Resources,Recruiter,2026-02-30,149452.0,Meets

#checking unique values on department column.

In [53]:
df ["department"].unique()

<StringArray>
['Human Resources', 'Finance', 'Sales', 'Engineering', 'Marketing']
Length: 5, dtype: str

#removing extra spaces.

In [51]:
df["department"] = df["department"].str.strip().str.title()
df["department"].unique()

<StringArray>
['Human Resources', 'Finance', 'Sales', 'Engineering', 'Marketing']
Length: 5, dtype: str

#converting missing, unnecessary and negative values to nan, converting valid salary values to numeric values and checking whether any negative salary values remained.

In [54]:

def cleaned_salary(val):
    if pd.isna(val) or val == "CONFIDENTIAL":
        return np.nan
   
   
    num = float(val)
    
    if num > 0:
        return num
    else:
        return np.nan


df["salary"] = df["salary"].apply(cleaned_salary)

df[df["salary"] < 0]

Empty DataFrame
Columns: [employee_id, full_name, department, job_title, hire_date, salary, performance_score]
Index: []

#checking the entire file.

In [55]:
df

,employee_id,full_name,department,job_title,hire_date,salary,performance_score
1,EMP_1107,Employee_1107,Human Resources,Recruiter,2021-12-13,NaN,Meets
2,EMP_1739,Employee_1739,Finance,Financial Analyst,2019-04-05,119127.0,Exceeds
3,EMP_1140,Employee_1140,Finance,Financial Analyst,2022-07-15,114827.0,Needs Improvement
4,EMP_2018,Employee_2018,Sales,Account Executive,2024-08-31,56382.0,Meets
5,EMP_1527,Employee_1527,Engineering,Software Engineer,2020-06-29,139659.0,Meets
...,...,...,...,...,...,...,...
1119,EMP_1330,Employee_1330,Sales,Account Executive,2026-02-30,145421.0,Needs Improvement
1120,EMP_1466,Employee_1466,Marketing,SEO Specialist,2023-01-17,121344.0,Exceeds
1121,EMP_1121,Employee_1121,Finance,Accountant,2021-01-30,45772.0,Meets
1122,EMP_2044,Employee_2044,Sales,Sales Manager,Active Employee,136520.0,Needs Improvement
1124,EMP_1860,Employee_1860,Human Resources,Recruiter,2026-02-30,149452.0,Meets

#saving the cleaned file.

In [56]:
df.to_csv('hr_cleaned_portfolio.csv', index=False)

#The remaining data cleaning and transformation will be performed in Power BI before creating the final dashboard#